// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: dharma.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_dharma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_dharma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_dharma_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_dharma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dharma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_dharma_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EMCONRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Active        bool                   `protobuf:"varint,1,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EMCONRequest) Reset() {
	*x = EMCONRequest{}
	mi := &file_dharma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EMCONRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EMCONRequest) ProtoMessage() {}

func (x *EMCONRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dharma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EMCONRequest.ProtoReflect.Descriptor instead.
func (*EMCONRequest) Descriptor() ([]byte, []int) {
	return file_dharma_proto_rawDescGZIP(), []int{2}
}

func (x *EMCONRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_dharma_proto protoreflect.FileDescriptor

const file_dharma_proto_rawDesc = "" +
	"\n" +
	"\fdharma.proto\x12\x06dharma\"\a\n" +
	"\x05Empty\"B\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\fEMCONRequest\x12\x16\n" +
	"\x06active\x18\x01 \x01(\bR\x06active2\xe8\x01\n" +
	"\rDharmaService\x123\n" +
	"\n" +
	"NodeStatus\x12\r.dharma.Empty\x1a\x16.dharma.StatusResponse\x121\n" +
	"\bNodeBoot\x12\r.dharma.Empty\x1a\x16.dharma.StatusResponse\x125\n" +
	"\fNodeLockdown\x12\r.dharma.Empty\x1a\x16.dharma.StatusResponse\x128\n" +
	"\bSetEMCON\x12\x14.dharma.EMCONRequest\x1a\x16.dharma.StatusResponseB(Z&github.com/dharma-zt/dharma-zt/pkg/apib\x06proto3"

var (
	file_dharma_proto_rawDescOnce sync.Once
	file_dharma_proto_rawDescData []byte
)

func file_dharma_proto_rawDescGZIP() []byte {
	file_dharma_proto_rawDescOnce.Do(func() {
		file_dharma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dharma_proto_rawDesc), len(file_dharma_proto_rawDesc)))
	})
	return file_dharma_proto_rawDescData
}

var file_dharma_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_dharma_proto_goTypes = []any{
	(*Empty)(nil),          // 0: dharma.Empty
	(*StatusResponse)(nil), // 1: dharma.StatusResponse
	(*EMCONRequest)(nil),   // 2: dharma.EMCONRequest
}
var file_dharma_proto_depIdxs = []int32{
	0, // 0: dharma.DharmaService.NodeStatus:input_type -> dharma.Empty
	0, // 1: dharma.DharmaService.NodeBoot:input_type -> dharma.Empty
	0, // 2: dharma.DharmaService.NodeLockdown:input_type -> dharma.Empty
	2, // 3: dharma.DharmaService.SetEMCON:input_type -> dharma.EMCONRequest
	1, // 4: dharma.DharmaService.NodeStatus:output_type -> dharma.StatusResponse
	1, // 5: dharma.DharmaService.NodeBoot:output_type -> dharma.StatusResponse
	1, // 6: dharma.DharmaService.NodeLockdown:output_type -> dharma.StatusResponse
	1, // 7: dharma.DharmaService.SetEMCON:output_type -> dharma.StatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dharma_proto_init() }
func file_dharma_proto_init() {
	if File_dharma_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dharma_proto_rawDesc), len(file_dharma_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dharma_proto_goTypes,
		DependencyIndexes: file_dharma_proto_depIdxs,
		MessageInfos:      file_dharma_proto_msgTypes,
	}.Build()
	File_dharma_proto = out.File
	file_dharma_proto_goTypes = nil
	file_dharma_proto_depIdxs = nil
}
