// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: dharma.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DharmaService_NodeStatus_FullMethodName   = "/dharma.DharmaService/NodeStatus"
	DharmaService_NodeBoot_FullMethodName     = "/dharma.DharmaService/NodeBoot"
	DharmaService_NodeLockdown_FullMethodName = "/dharma.DharmaService/NodeLockdown"
	DharmaService_SetEMCON_FullMethodName     = "/dharma.DharmaService/SetEMCON"
)

// DharmaServiceClient is the client API for DharmaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DharmaServiceClient interface {
	NodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	NodeBoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	NodeLockdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	SetEMCON(ctx context.Context, in *EMCONRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type dharmaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDharmaServiceClient(cc grpc.ClientConnInterface) DharmaServiceClient {
	return &dharmaServiceClient{cc}
}

func (c *dharmaServiceClient) NodeStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DharmaService_NodeStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dharmaServiceClient) NodeBoot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DharmaService_NodeBoot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dharmaServiceClient) NodeLockdown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DharmaService_NodeLockdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dharmaServiceClient) SetEMCON(ctx context.Context, in *EMCONRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, DharmaService_SetEMCON_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DharmaServiceServer is the server API for DharmaService service.
// All implementations must embed UnimplementedDharmaServiceServer
// for forward compatibility.
type DharmaServiceServer interface {
	NodeStatus(context.Context, *Empty) (*StatusResponse, error)
	NodeBoot(context.Context, *Empty) (*StatusResponse, error)
	NodeLockdown(context.Context, *Empty) (*StatusResponse, error)
	SetEMCON(context.Context, *EMCONRequest) (*StatusResponse, error)
	mustEmbedUnimplementedDharmaServiceServer()
}

// UnimplementedDharmaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDharmaServiceServer struct{}

func (UnimplementedDharmaServiceServer) NodeStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeStatus not implemented")
}
func (UnimplementedDharmaServiceServer) NodeBoot(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeBoot not implemented")
}
func (UnimplementedDharmaServiceServer) NodeLockdown(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NodeLockdown not implemented")
}
func (UnimplementedDharmaServiceServer) SetEMCON(context.Context, *EMCONRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetEMCON not implemented")
}
func (UnimplementedDharmaServiceServer) mustEmbedUnimplementedDharmaServiceServer() {}
func (UnimplementedDharmaServiceServer) testEmbeddedByValue()                       {}

// UnsafeDharmaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DharmaServiceServer will
// result in compilation errors.
type UnsafeDharmaServiceServer interface {
	mustEmbedUnimplementedDharmaServiceServer()
}

func RegisterDharmaServiceServer(s grpc.ServiceRegistrar, srv DharmaServiceServer) {
	// If the following call panics, it indicates UnimplementedDharmaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DharmaService_ServiceDesc, srv)
}

func _DharmaService_NodeStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DharmaServiceServer).NodeStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DharmaService_NodeStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DharmaServiceServer).NodeStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DharmaService_NodeBoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DharmaServiceServer).NodeBoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DharmaService_NodeBoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DharmaServiceServer).NodeBoot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DharmaService_NodeLockdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DharmaServiceServer).NodeLockdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DharmaService_NodeLockdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DharmaServiceServer).NodeLockdown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DharmaService_SetEMCON_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EMCONRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DharmaServiceServer).SetEMCON(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DharmaService_SetEMCON_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DharmaServiceServer).SetEMCON(ctx, req.(*EMCONRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DharmaService_ServiceDesc is the grpc.ServiceDesc for DharmaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DharmaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dharma.DharmaService",
	HandlerType: (*DharmaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NodeStatus",
			Handler:    _DharmaService_NodeStatus_Handler,
		},
		{
			MethodName: "NodeBoot",
			Handler:    _DharmaService_NodeBoot_Handler,
		},
		{
			MethodName: "NodeLockdown",
			Handler:    _DharmaService_NodeLockdown_Handler,
		},
		{
			MethodName: "SetEMCON",
			Handler:    _DharmaService_SetEMCON_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dharma.proto",
}
