// Code generated by bpf2go; DO NOT EDIT.

package ebpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfConnState struct {
	_     structs.HostLayout
	State uint32
}

type bpfFlowTuple struct {
	_       structs.HostLayout
	SrcIp   uint32
	DstIp   uint32
	SrcPort uint16
	DstPort uint16
}

type bpfTokenBucket struct {
	_          structs.HostLayout
	Tokens     uint64
	LastUpdate uint64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TcEgress         *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress        *ebpf.ProgramSpec `ebpf:"tc_ingress"`
	XdpIngressFilter *ebpf.ProgramSpec `ebpf:"xdp_ingress_filter"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	AllowedPeers *ebpf.MapSpec `ebpf:"allowed_peers"`
	ConnTrack    *ebpf.MapSpec `ebpf:"conn_track"`
	RateLimiter  *ebpf.MapSpec `ebpf:"rate_limiter"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	AllowedPeers *ebpf.Map `ebpf:"allowed_peers"`
	ConnTrack    *ebpf.Map `ebpf:"conn_track"`
	RateLimiter  *ebpf.Map `ebpf:"rate_limiter"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.AllowedPeers,
		m.ConnTrack,
		m.RateLimiter,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TcEgress         *ebpf.Program `ebpf:"tc_egress"`
	TcIngress        *ebpf.Program `ebpf:"tc_ingress"`
	XdpIngressFilter *ebpf.Program `ebpf:"xdp_ingress_filter"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TcEgress,
		p.TcIngress,
		p.XdpIngressFilter,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpf.o
var _BpfBytes []byte
